/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/game/GameEndView.ls
 */
export class GameEndViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public dragBox!: Laya.Box;
    public starBox!: Laya.Box;
    public resultBg!: Laya.Button;
    public result!: Laya.Button;
    public backBtn!: Laya.Button;
    public restartBtn!: Laya.Button;
}

