/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/game/GamePlayerView.ls
 */
export class GamePlayerViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Button;
    public starList!: Laya.List;
    public timeBg!: Laya.Image;
    public timeDown!: Laya.Label;
    public timeCircle!: Laya.Image;
    public gameTarget!: Laya.TextInput;
    public middleBox!: Laya.Box;
    public gameBox!: Laya.Box;
    public gameIcon!: Laya.Image;
    public chooseBox!: Laya.Box;
    public toolBox!: Laya.VBox;
    public helpBox!: Laya.Box;
    public helpNum!: Laya.Label;
    public timeBox!: Laya.Box;
    public timeNum!: Laya.Label;
    public maskBox!: Laya.Box;
    public gameTip!: Laya.Image;
    public tipMask!: Laya.Sprite;
    public clickBox!: Laya.Box;
    public findNum!: Laya.Label;
}

