/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/game/ResurgenceView.ls
 */
export class ResurgenceViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public dragBox!: Laya.Box;
    public toolIcon!: Laya.Image;
    public toolTip!: Laya.Label;
    public cancelBtn!: Laya.Button;
    public sureBtn!: Laya.Button;
}

