/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/game/SubjectPlayView.ls
 */
export class SubjectPlayViewBase extends Laya.Scene {
    public middleBox!: Laya.Box;
    public gameList!: Laya.List;
    public backBtn!: Laya.Image;
}

