/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/home/ConfirmView.ls
 */
export class ConfirmViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public dragBox!: Laya.Box;
    public confirmTip!: Laya.Label;
    public closeBtn!: Laya.Image;
    public cancelBtn!: Laya.Image;
    public sureBtn!: Laya.Image;
}

