/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/home/GameCommentView.ls
 */
export class GameCommentViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public drag!: Laya.Image;
    public commentList!: Laya.Panel;
    public tipNull!: Laya.Box;
    public sendInput!: Laya.TextInput;
    public sendBtn!: Laya.Image;
}

