/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/home/HomeView.ls
 */
export class HomeViewBase extends Laya.Scene {
    public middleBox!: Laya.Box;
    public listBox!: Laya.Box;
    public gameFollwList!: Laya.List;
    public gameRecommendList!: Laya.List;
    public tipFollowNull!: Laya.Box;
    public tipRecommnedNull!: Laya.Box;
    public topBox!: Laya.Box;
    public rankBtn!: Laya.Button;
    public followBtn!: Laya.Label;
    public recomendBtn!: Laya.Label;
    public diamonds!: Laya.Label;
    public pageBox!: Laya.Box;
    public bottomBox!: Laya.Box;
    public tabBox!: Laya.HBox;
    public homeBox!: Laya.Box;
    public createBox!: Laya.Box;
    public myBox!: Laya.Box;
    public createTip!: Laya.Box;
}

