/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/home/ListChooseView.ls
 */
export class ListChooseViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public dragBox!: Laya.Box;
    public drag!: Laya.Image;
    public chooseList!: Laya.List;
    public cancelBtn!: Laya.Label;
}

