/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/home/ListSelectView.ls
 */
export class ListSelectViewBase extends Laya.Scene {
    public dragBox!: Laya.Box;
    public title!: Laya.Label;
    public menuList!: Laya.List;
}

