/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/home/PraiseView.ls
 */
export class PraiseViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public dragBox!: Laya.Box;
    public confirmTip!: Laya.Label;
    public sureBtn!: Laya.Image;
}

