/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { RankItem } from "../../item/RankItem";

/**
 * scene/home/RankView.ls
 */
export class RankViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public ruleBtn!: Laya.Image;
    public listBox!: Laya.Box;
    public playerSort!: Laya.Label;
    public gameSort!: Laya.Label;
    public creatSort!: Laya.Label;
    public selectTab!: Laya.Image;
    public tipNull!: Laya.Box;
    public rankList!: Laya.List;
    public myBox!: Laya.Box;
    public myItem!: RankItem;
}

