/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/home/RankRuleView.ls
 */
export class RankRuleViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public dragBox!: Laya.Box;
    public rewardBox!: Laya.Box;
    public rewardList!: Laya.List;
    public ruleBox!: Laya.Box;
    public ruleArea!: Laya.TextArea;
    public rewardBtn!: Laya.Button;
    public ruleBtn!: Laya.Button;
    public closeBtn!: Laya.Image;
}

