/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { SearchBox } from "../../item/SearchBox";

/**
 * scene/home/SearchView.ls
 */
export class SearchViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public title!: Laya.Label;
    public searchBox!: SearchBox;
    public searchTipBox!: Laya.Box;
    public historyBox!: Laya.Box;
    public clearHistory!: Laya.Image;
    public historyPanel!: Laya.Panel;
    public recommendBox!: Laya.Box;
    public refreshRecommend!: Laya.Image;
    public recommendList!: Laya.List;
    public resultBox!: Laya.Box;
    public allSort!: Laya.Label;
    public userSort!: Laya.Label;
    public gameSort!: Laya.Label;
    public selectTab!: Laya.Image;
    public tipNull!: Laya.Box;
    public resultList!: Laya.Panel;
}

