/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/home/TipView.ls
 */
export class TipViewBase extends Laya.Scene {
    public tipBox!: Laya.Box;
    public bg!: Laya.Image;
    public tip!: Laya.Label;
    public loadBox!: Laya.Box;
    public loading!: Laya.Animation;
    public loadTip!: Laya.Label;
    public generateBox!: Laya.Box;
    public generate!: Laya.Animation;
    public generateTip!: Laya.Label;
}

