/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/author.lh
 */
export class AuthorBase extends Laya.Box {
    public authorName!: Laya.Label;
    public authorIcon!: Laya.Image;
}

