/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";
import { GameItem } from "./GameItem";

/**
 * prefab/chatItem.lh
 */
export class ChatItemBase extends Laya.Box {
    public head!: Head;
    public chatBg!: Laya.Image;
    public chatLabel!: Laya.Label;
    public gameItem!: GameItem;
    public gameDelete!: Laya.Box;
    public chatTime!: Laya.Label;
}

