/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";
import { Author } from "./Author";

/**
 * prefab/commentItem.lh
 */
export class CommentItemBase extends Laya.Box {
    public downImage!: Laya.Image;
    public head!: Head;
    public headInfo!: Laya.Box;
    public author!: Author;
    public commentDes!: Laya.Label;
    public replyBox!: Laya.Box;
    public commentTime!: Laya.Label;
    public reply!: Laya.Label;
    public endBox!: Laya.Box;
    public subcommentList!: Laya.Panel;
    public unfoldBtn!: Laya.HBox;
    public foldBtn!: Laya.HBox;
    public likeBtn!: Laya.Button;
    public likeNum!: Laya.Label;
}

