/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/editItem.lh
 */
export class EditItemBase extends Laya.Box {
    public icon!: Laya.Image;
    public index!: Laya.Label;
    public delete!: Laya.Image;
}

