/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/freeslider.lh
 */
export class FreeSliderBase extends Laya.Box {
    public slider!: Laya.HSlider;
    public tip!: Laya.Image;
    public tipNum!: Laya.Label;
}

