/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";

/**
 * prefab/gameItem.lh
 */
export class GameItemBase extends Laya.Box {
    public gameIcon!: Laya.Image;
    public gameMask!: Laya.Sprite;
    public head!: Head;
    public gameName!: Laya.Label;
    public play!: Laya.Image;
    public playerNum!: Laya.Label;
    public edit!: Laya.Image;
}

