/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/game.lh
 */
export class GameBase extends Laya.Box {
    public gameIcon!: Laya.Image;
    public gameMask!: Laya.Sprite;
}

