/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/head.lh
 */
export class HeadBase extends Laya.Box {
    public headIcon!: Laya.Image;
    public headMask!: Laya.Sprite;
}

