/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/historyItem.lh
 */
export class HistoryItemBase extends Laya.Box {
    public tab!: Laya.Label;
}

