/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/interest.lh
 */
export class InterestBase extends Laya.Box {
    public tab!: Laya.Label;
}

