/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";
import { Game } from "./Game";

/**
 * prefab/messageItem.lh
 */
export class MessageItemBase extends Laya.Box {
    public highLight!: Laya.Image;
    public head!: Head;
    public names!: Laya.Label;
    public desc!: Laya.Label;
    public time!: Laya.Label;
    public game!: Game;
    public chatBtn!: Laya.Button;
    public stateBtn!: Laya.Button;
}

