/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/musicItem.lh
 */
export class MusicItemBase extends Laya.Box {
    public names!: Laya.Label;
    public desc!: Laya.Label;
    public moreBtn!: Laya.Image;
}

