/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";

/**
 * prefab/playGameItem.lh
 */
export class PlayGameItemBase extends Laya.Box {
    public gameBg!: Laya.Image;
    public starBg!: Laya.Image;
    public starList!: Laya.List;
    public socailBox!: Laya.VBox;
    public likeBox!: Laya.Box;
    public commentBox!: Laya.Box;
    public collectBox!: Laya.Box;
    public shareBox!: Laya.Box;
    public info!: Laya.Box;
    public head!: Head;
    public gameName!: Laya.Label;
    public authorName!: Laya.Label;
    public followBtn!: Laya.Button;
    public gameDesc!: Laya.Label;
    public playBox!: Laya.Box;
    public playBtn!: Laya.Image;
}

