/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";
import { Game } from "./Game";

/**
 * prefab/rankItem.lh
 */
export class RankItemBase extends Laya.Box {
    public selfBg!: Laya.Image;
    public rankBg!: Laya.Image;
    public rankNum!: Laya.Label;
    public head!: Head;
    public names!: Laya.Label;
    public game!: Game;
    public gameName!: Laya.Label;
    public info!: Laya.Image;
    public infoIcon!: Laya.Image;
    public infoNum!: Laya.Label;
}

