/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";

/**
 * prefab/searchGameItem.lh
 */
export class SearchGameItemBase extends Laya.Box {
    public icon!: Laya.Image;
    public head!: Head;
    public playerNum!: Laya.Label;
    public gameName!: Laya.Label;
    public gameDesc!: Laya.Label;
    public authorName!: Laya.Label;
}

