/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/searchGroupItem.lh
 */
export class SearchGroupItemBase extends Laya.Box {
    public title!: Laya.Label;
    public more!: Laya.Label;
    public gameList!: Laya.List;
    public userList!: Laya.List;
}

