/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/searchBox.lh
 */
export class SearchBoxBase extends Laya.Box {
    public searchIcon!: Laya.Image;
    public searchInput!: Laya.TextInput;
    public cancelBtn!: Laya.Image;
}

