/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/setItem.lh
 */
export class SetItemBase extends Laya.Box {
    public title!: Laya.Label;
    public contentList!: Laya.List;
}

