/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";
import { Author } from "./Author";

/**
 * prefab/subcommentItem.lh
 */
export class SubcommentItemBase extends Laya.Box {
    public downImage!: Laya.Image;
    public head!: Head;
    public headInfo!: Laya.HBox;
    public leftauthor!: Author;
    public rightauthor!: Author;
    public commentDes!: Laya.Label;
    public replyBox!: Laya.Box;
    public commentTime!: Laya.Label;
    public reply!: Laya.Label;
    public likeBtn!: Laya.Button;
    public likeNum!: Laya.Label;
}

