/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "./Head";

/**
 * prefab/userItem.lh
 */
export class UserItemBase extends Laya.Box {
    public head!: Head;
    public names!: Laya.Label;
    public black!: Laya.Image;
    public fans!: Laya.Label;
    public userid!: Laya.Label;
    public follow!: Laya.Button;
    public chatBtn!: Laya.Image;
    public setBtn!: Laya.Image;
}

