/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { FreeSlider } from "../../item/FreeSlider";

/**
 * scene/edit/DescView.ls
 */
export class DescViewBase extends Laya.Scene {
    public dragBox!: Laya.Box;
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public descnput!: Laya.TextInput;
    public descNum!: Laya.Label;
    public bg!: Laya.Image;
    public loadIcon!: Laya.Image;
    public uploadBtn!: Laya.Image;
    public deleteBtn!: Laya.Image;
    public iconBox!: Laya.Box;
    public slider!: FreeSlider;
    public reloadBtn!: Laya.Button;
    public useBtn!: Laya.Button;
    public generateBtn!: Laya.Button;
    public free!: Laya.Image;
    public video!: Laya.Button;
    public freeNum!: Laya.Label;
    public stimulateBg!: Laya.Image;
    public stimulateNum!: Laya.Label;
}

