/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/edit/EditModeView.ls
 */
export class EditorModeViewBase extends Laya.Scene {
    public createBox!: Laya.Box;
    public modeBox!: Laya.Box;
    public modeList!: Laya.List;
    public draftBox!: Laya.Box;
    public draftName!: Laya.Label;
    public draftList!: Laya.List;
}

