/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/edit/EditSourceView.ls
 */
export class EditorSourceViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public drag!: Laya.Image;
    public icon!: Laya.Image;
    public sureBtn!: Laya.Button;
}

