/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/edit/EditMusicView.ls
 */
export class EditorMusicViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public drag!: Laya.Image;
    public musicName!: Laya.Label;
    public musicDesc!: Laya.Label;
    public cancelBtn!: Laya.Image;
    public sureBtn!: Laya.Image;
}

