/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/edit/GameEditView.ls
 */
export class GameEditorViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Button;
    public playBtn!: Laya.Button;
    public saveBtn!: Laya.Button;
    public musicBtn!: Laya.Button;
    public publishBtn!: Laya.Button;
    public numTip!: Laya.Label;
    public middleBox!: Laya.Box;
    public editBox!: Laya.Box;
    public gameIcon!: Laya.Image;
    public gameMask!: Laya.Image;
    public chooseBox!: Laya.Box;
    public pointBox!: Laya.Box;
    public leftBox!: Laya.Box;
    public add!: Laya.Button;
    public reduce!: Laya.Button;
    public redo!: Laya.Button;
    public undo!: Laya.Button;
    public reset!: Laya.Button;
    public cut!: Laya.Button;
    public bottomBox!: Laya.Box;
    public descInput!: Laya.TextInput;
    public guideBox!: Laya.Box;
    public guideTip!: Laya.Label;
}

