/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/edit/MusicView.ls
 */
export class MusicViewBase extends Laya.Scene {
    public dragBox!: Laya.Box;
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public nameInput!: Laya.TextInput;
    public nameNum!: Laya.Label;
    public descnput!: Laya.TextInput;
    public descNum!: Laya.Label;
    public selectTab!: Laya.Image;
    public allSort!: Laya.Label;
    public mySort!: Laya.Label;
    public tipNull!: Laya.Box;
    public sortList!: Laya.List;
    public libraryList!: Laya.List;
    public generateBtn!: Laya.Button;
}

