/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/edit/PublishView.ls
 */
export class PublishViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public drag!: Laya.Image;
    public logoIcon!: Laya.Image;
    public nameInput!: Laya.TextInput;
    public nameNum!: Laya.Label;
    public descInput!: Laya.TextInput;
    public descNum!: Laya.Label;
    public minuteList!: Laya.List;
    public secondList!: Laya.List;
    public publishBtn!: Laya.Button;
    public effectBox!: Laya.Box;
    public publishEffect!: Laya.Animation;
    public publishSuccessBtn!: Laya.Button;
}

