/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/edit/TagChooseView.ls
 */
export class TagChooseViewBase extends Laya.Scene {
    public bg!: Laya.Box;
    public dragBox!: Laya.Box;
    public drag!: Laya.Image;
    public tagList!: Laya.List;
    public sureBtn!: Laya.Button;
}

