/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/message/ChatView.ls
 */
export class ChatViewBase extends Laya.Scene {
    public chatList!: Laya.Panel;
    public bottomBox!: Laya.Box;
    public inputBox!: Laya.Box;
    public sendInput!: Laya.TextInput;
    public sendBtn!: Laya.Button;
    public changeBtn!: Laya.Image;
    public listBox!: Laya.Box;
    public createSort!: Laya.Label;
    public likeSort!: Laya.Label;
    public collectSort!: Laya.Label;
    public selectTab!: Laya.Image;
    public tipNull!: Laya.Box;
    public gameList!: Laya.List;
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public title!: Laya.Label;
}

