/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/message/MessageView.ls
 */
export class MessageViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public listBox!: Laya.Box;
    public allSort!: Laya.Label;
    public privateSort!: Laya.Label;
    public officialSort!: Laya.Label;
    public commentSort!: Laya.Label;
    public fanSort!: Laya.Label;
    public selectTab!: Laya.Image;
    public tipNull!: Laya.Box;
    public messageList!: Laya.List;
}

