/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/info/AboutView.ls
 */
export class AboutViewBase extends Laya.Scene {
    public contentList!: Laya.List;
    public version!: Laya.Label;
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
}

