/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "../../item/Head";

/**
 * scene/info/EditInfoView.ls
 */
export class EditInfoViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public infoBox!: Laya.Box;
    public head!: Head;
    public editList!: Laya.List;
    public sloganInput!: Laya.TextInput;
    public sloganNum!: Laya.Label;
    public saveBtn!: Laya.Button;
}

