/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/info/EditIconView.ls
 */
export class EditIconViewBase extends Laya.Scene {
    public headBox!: Laya.Box;
    public headIcon!: Laya.Image;
    public maskBox!: Laya.Box;
    public sureBtn!: Laya.Button;
    public tip!: Laya.Label;
    public maskheadIcon!: Laya.Image;
    public maskbgIcon!: Laya.Image;
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public title!: Laya.Label;
}

