/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/info/EditInterestView.ls
 */
export class EditInterestViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public tipNum!: Laya.Label;
    public tabBg!: Laya.Box;
    public tabList!: Laya.List;
}

