/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/info/PlayerSettingView.ls
 */
export class PlayerSettingViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public content!: Laya.Box;
    public listBox!: Laya.Panel;
    public loginOutBtn!: Laya.Button;
}

