/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { Head } from "../../item/Head";

/**
 * scene/info/PlayerInfoView.ls
 */
export class PlayerInfoViewBase extends Laya.Scene {
    public playerBg!: Laya.Image;
    public topBox!: Laya.Box;
    public otherName!: Laya.Label;
    public Panel!: Laya.Panel;
    public myBtnBox!: Laya.HBox;
    public message!: Laya.Box;
    public messageTip!: Laya.Image;
    public editInfo!: Laya.Box;
    public setting!: Laya.Box;
    public otherBtnBox!: Laya.HBox;
    public followBtn!: Laya.Button;
    public chatBtn!: Laya.Button;
    public listBox!: Laya.Box;
    public createSort!: Laya.Label;
    public historySort!: Laya.Label;
    public likeSort!: Laya.Label;
    public likeLock!: Laya.Image;
    public collectSort!: Laya.Label;
    public collectLock!: Laya.Image;
    public selectTab!: Laya.Image;
    public gameList!: Laya.List;
    public tips!: Laya.Box;
    public tipsIcon!: Laya.Image;
    public tipsTxt!: Laya.Label;
    public infoBox!: Laya.Box;
    public head!: Head;
    public nickName!: Laya.Label;
    public slogan!: Laya.Label;
    public follow!: Laya.Box;
    public fan!: Laya.Box;
    public praise!: Laya.Box;
    public backBox!: Laya.Box;
    public backBtn!: Laya.Image;
}

