/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/info/PreviewIconView.ls
 */
export class PreviewIconViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public title!: Laya.Label;
    public previewBox!: Laya.Box;
    public previewIcon!: Laya.Image;
    public btnBox!: Laya.Box;
    public auditInfo!: Laya.Label;
    public changeBtn!: Laya.Button;
}

