/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { SearchBox } from "../../item/SearchBox";

/**
 * scene/info/SocailView.ls
 */
export class SocailViewBase extends Laya.Scene {
    public topBox!: Laya.Box;
    public backBtn!: Laya.Image;
    public listBox!: Laya.Box;
    public friendSort!: Laya.Label;
    public followSort!: Laya.Label;
    public fanSort!: Laya.Label;
    public selectTab!: Laya.Image;
    public searchBox!: SearchBox;
    public tipNull!: Laya.Box;
    public userList!: Laya.List;
}

