/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/login/LoginView.ls
 */
export class LoginViewBase extends Laya.Scene {
    public loading!: Laya.ProgressBar;
    public star!: Laya.Image;
}

